name: watchmate_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cached_network_image: ^3.4.1
  shared_preferences: ^2.5.3
  cupertino_icons: ^1.0.8
  country_picker: ^2.0.27
  flutter_bloc: ^9.1.1
  go_router: ^16.0.0
  loading_animation_widget: ^1.3.0
  dio: ^5.8.0+1
  get_it: ^8.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  adaptive_icon_foreground: "assets/images/icons/app_icon.png"
  image_path: "assets/images/icons/app_icon.png"
  adaptive_icon_background: "#0F172A"
  android: "launcher_icon"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/images/icons/
    - assets/

  fonts:
    - family: Bold
      fonts:
        - asset: assets/fonts/bold.woff
    - family: SemiBold
      fonts:
        - asset: assets/fonts/semibold.woff
    - family: Medium
      fonts:
        - asset: assets/fonts/medium.woff
    - family: Regular
      fonts:
        - asset: assets/fonts/regular.woff
    - family: ExtraBold
      fonts:
        - asset: assets/fonts/extrabold.woff2
  
