name: watchmate_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  loading_animation_widget: ^1.3.0
  background_downloader: ^9.2.3
  cached_network_image: ^3.4.1
  shared_preferences: ^2.5.3
  socket_io_client: ^3.1.2
  cupertino_icons: ^1.0.8
  video_thumbnail: ^0.5.6
  country_picker: ^2.0.27
  flutter_dotenv: ^5.2.1
  path_provider: ^2.1.5
  video_player: ^2.10.0
  file_picker: ^10.2.2
  flutter_bloc: ^9.1.1
  go_router: ^16.0.0
  equatable: ^2.0.7
  app_links: ^6.4.0
  shimmer: ^3.0.0
  chewie: ^1.12.1
  rxdart: ^0.28.0
  get_it: ^8.0.3
  dio: ^5.8.0+1
  intl: ^0.20.2
  path: ^1.9.1
  uuid: ^4.5.1
  share_plus: ^11.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0

flutter_launcher_icons:
  adaptive_icon_foreground: "assets/images/icons/app_icon.png"
  image_path: "assets/images/icons/app_icon.png"
  adaptive_icon_background: "#0F172A"
  android: "launcher_icon"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/images/backgrounds/
    - assets/images/icons/
    - assets/
    - .env

  fonts:
    - family: Bold
      fonts:
        - asset: assets/fonts/bold.woff
    - family: SemiBold
      fonts:
        - asset: assets/fonts/semibold.woff
    - family: Medium
      fonts:
        - asset: assets/fonts/medium.woff
    - family: Regular
      fonts:
        - asset: assets/fonts/regular.woff
    - family: ExtraBold
      fonts:
        - asset: assets/fonts/extrabold.woff2
  
